#!/bin/sh

if [ `uname` = "Darwin" ] ; then
    if test ! -x /usr/local/bin/python3 ; then
        echo "Please install Python3 for Mac OS X first"
        exit 1
    fi
fi

VENV_DIR=".venv"

if test ! -d $VENV_DIR ; then
    # Create fresh virtual environment
    python3 -m venv
fi
. $VENV_DIR/bin/activate

pip install --upgrade -r requirements/dev.txt
export DJANGO_SETTINGS_MODULE="website.settings.dev"
python3 manage.py migrate
