# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_de', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('title_nl', models.CharField(max_length=200, null=True)),
                ('title_es', models.CharField(max_length=200, null=True)),
                ('title_it', models.CharField(max_length=200, null=True)),
                ('body', models.TextField()),
                ('body_en', models.TextField(null=True)),
                ('body_de', models.TextField(null=True)),
                ('body_fr', models.TextField(null=True)),
                ('body_nl', models.TextField(null=True)),
                ('body_es', models.TextField(null=True)),
                ('body_it', models.TextField(null=True)),
                ('type', models.CharField(choices=[('info', 'Information'), ('update', 'Update notice'), ('kill', 'App disabled')], default='info', max_length=10)),
            ],
            options={
                'ordering': ['type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version string, e.g. 1.2.3', max_length=200)),
                ('messages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Message')),
            ],
        ),
    ]
