# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Flavor name, e.g. "universal"', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Platform name, e.g. "iOS"', max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='version',
            old_name='messages',
            new_name='message',
        ),
        migrations.AddField(
            model_name='version',
            name='comment',
            field=models.CharField(blank=True, help_text='Add any information here (not returned by API)', max_length=200),
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(help_text='Version string, e.g. "1.2.3"', max_length=32),
        ),
        migrations.AddField(
            model_name='flavor',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Platform'),
        ),
        migrations.AddField(
            model_name='version',
            name='flavor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='notifications.Platform'),
            preserve_default=False,
        ),
    ]
