# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 09:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20151216_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productflavor',
            name='title',
            field=models.CharField(help_text='Flavor name, e.g. "universal"', max_length=64, validators=[django.core.validators.RegexValidator(message='Only alphanumerics or characters allowed', regex='\\w+')]),
        ),
        migrations.AlterField(
            model_name='productplatform',
            name='title',
            field=models.CharField(help_text='Platform name, e.g. "iOS"', max_length=64, validators=[django.core.validators.RegexValidator(message='Only alphanumerics or characters allowed', regex='\\w+')]),
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(help_text='Version string, e.g. "1.2.3"', max_length=32, validators=[django.core.validators.RegexValidator(message="Only alphanumerics, characters and '.' allowed", regex='[\\w.]+')]),
        ),
    ]
