# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20151209_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Flavor'),
        ),
    ]
