# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20151209_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flavor',
            new_name='ProductFlavor',
        ),
        migrations.RenameModel(
            old_name='Platform',
            new_name='ProductPlatform',
        ),
    ]
