# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20160125_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='body_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='body_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title_pt_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title_zh',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
