# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20160128_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body_zh',
            new_name='body_zh_cn',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='title_zh',
            new_name='title_zh_cn',
        ),
    ]
